### PR TITLE
New tagline

### PR DESCRIPTION
**Pull request by quanganhdo**
Task/Issue URL: https://app.asana.com/0/1205591970852438/1208504563612286/f
Tech Design URL:
CC:

**Description**:

Updates new tagline.

**Steps to test this PR**:
1. Check the About page

**Definition of Done**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

---
###### Internal references:
[Pull Request Review Checklist](https://app.asana.com/0/1202500774821704/1203764234894239/f)
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277482/f)

### CODE REVIEW

**Comment by quanganhdo** [comment]
* **#3401** <a href="https://app.graphite.dev/github/pr/duckduckgo/macos-browser/3401?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @quanganhdo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by federicocappelli — APPROVED** [review]
LGTM
Suggestion: should we write the new tagline in a single place (like some test utilities) and re-use it across all UI tests instead than duplicate it many times?

**Comment by quanganhdo** [comment]
@federicocappelli That sounds overkill to me; how often do the tagline need to be updated? :D

**Comment by federicocappelli** [comment]
> @federicocappelli That sounds overkill to me; how often do the tagline need to be updated? :D

Not the point, the localisation script every time is run extracts all these strings and localise them. A string should be in a single place for the same reason we use constants around the code, duplication can bring to mistakes.
But up to you, it's already approved.

**Pull request merged**
