### PR TITLE
Connect refactored update flow to the new release notes page

### PR DESCRIPTION
**Pull request by quanganhdo**
Task/Issue URL: https://app.asana.com/0/1199230911884351/1208183525704010/f
Tech Design URL:
CC:

**Description**:

Integrates with the new release note screen.

**Steps to test this PR**:
1. Refer to https://app.asana.com/0/1201037661562251/1208230039908704/f and use this build to check the behaviour: https://staticcdn.duckduckgo.com/macos-desktop-browser/a81f9679-e41d-404d-81a6-fd4a461d82f7/testbuilds/4be252d/duckduckgo-1.110.0.283.dmg

**Definition of Done**:

* [ ] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

---
###### Internal references:
[Pull Request Review Checklist](https://app.asana.com/0/1202500774821704/1203764234894239/f)
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277482/f)

### CODE REVIEW

**Comment by quanganhdo** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/duckduckgo/macos-browser/3411?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3411** <a href="https://app.graphite.dev/github/pr/duckduckgo/macos-browser/3411?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3274** <a href="https://app.graphite.dev/github/pr/duckduckgo/macos-browser/3274?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#3275](https://github.com/duckduckgo/macos-browser/pull/3275) <a href="https://app.graphite.dev/github/pr/duckduckgo/macos-browser/3275?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#3344](https://github.com/duckduckgo/macos-browser/pull/3344) <a href="https://app.graphite.dev/github/pr/duckduckgo/macos-browser/3344?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @quanganhdo and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by tomasstrba — COMMENTED** [review]
The code looks good to me, but I wasn't able to test this with success. When I click on "Restart to update", nothing happens. Any idea what's wrong?

Also, switching between Settings tab and Release notes tab when the update is available triggers the whole download process again.

**Comment by tomasstrba** [comment]
Adding a screen recording: (Click on the button has no effect)
testing

**Comment by quanganhdo** [comment]
> Also, switching between Settings tab and Release notes tab when the update is available triggers the whole download process again.

@tomasstrba This is caused by over-aggressive `checkForUpdate` calls. I'd add a `!hasPendingUpdate` check to take care of this. Lmk if you're good with a follow-up PR to add that logic. I'd rather get this chain of PR in main before tackling that edge case.

**Review by tomasstrba — APPROVED** [review]
✅ The new Release notes page correctly shows all the states and successfully triggers the update.

**Pull request merged**
