### PR TITLE
Disable sort and search when no bookmarks

### PR DESCRIPTION
**Pull request by jotaemepereira**
Task/Issue URL: https://app.asana.com/0/1204006570077678/1208262956542586/f
Tech Design URL:
CC:

## Description
It disables the sort and search buttons in the bookmarks manager and panel, when the user has no bookmarks.

### Acceptance criteria
**AC#1**
Given a user with no bookmarks, when the user opens the bookmarks panel then the sort and search button are disabled

**AC#2**
Given a user with no bookmarks, when the user opens the bookmarks manager then the sort and search button are disabled

**AC#3**
Given a user with no bookmarks, when the user adds a bookmark then the sort and search features are enabled

### Demo
https://github.com/user-attachments/assets/8d27720f-b637-4088-95a5-3ade649c3782

**Steps to test this PR**:
Verify the listed acceptance criteria are correct.

**Definition of Done**:

* [x] Does this PR satisfy our [Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

---
###### Internal references:
[Pull Request Review Checklist](https://app.asana.com/0/1202500774821704/1203764234894239/f)
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277482/f)

### CODE REVIEW

**Review by mallexxx — CHANGES_REQUESTED** [review]
Looks good overall but I found an issue: the search is still activated by Cmd+F shortcut or by typing a word with empty results; When clearing the search query empty screen is shown instead of the No bookmarks placeholder

**Comment by jotaemepereira** [comment]
> Looks good overall but I found an issue: the search is still activated by Cmd+F shortcut or by typing a word with empty results; When clearing the search query empty screen is shown instead of the No bookmarks placeholder

Great find @mallexxx. I missed that use case. I’ve added a fix for it, let me know what you think.

**Comment by mallexxx** [comment]
@jotaemepereira, better, but we need to disable entering the search mode when there‘s no bookmarks: now the bookmarks popover toolbar grows with the search field hidden when typing a letter or hitting Cmd+F; and search activates by itself if a bookmark is added while the popover is shown; I think we shouldn‘t enter the search mode at all while in empty state

**Comment by jotaemepereira** [comment]
> @jotaemepereira, better, but we need to disable entering the search mode when there‘s no bookmarks: now the bookmarks popover toolbar grows with the search field hidden when typing a letter or hitting Cmd+F; and search activates by itself if a bookmark is added while the popover is shown; I think we shouldn‘t enter the search mode at all while in empty state

Thanks. Fixed!

**Comment by mallexxx** [comment]
@jotaemepereira, I‘ve experimented a bit with key handlers and there were some inconsistencies like Find In Page activated when no bookmarks in the Bookmarks Popover or Esc key not deactivating search in Bookmarks Manager;
I ended up adding a Key Equivalent handling view in both the Popover and Manager and opened a PR on top of this PR:
https://github.com/duckduckgo/macos-browser/pull/3278

**Review by mallexxx — APPROVED** [review]

**Pull request merged**
